FROM tensorflow/tensorflow:latest-devel-gpu-py3

WORKDIR /estacion-de-trabajo

ADD . /estacion-de-trabajo

RUN pip install gym

# RUN apt-get install -y python3-numpy python3-dev cmake zlib1g-dev libjpeg-dev xvfb libav-tools xorg-dev python3-opengl libboost-all-dev libsdl2-dev swig






